//@version=5
indicator("BluPin Capital Buy/Sell Signal Indicator", overlay=true)

sources = input.source(defval=close, title="Source")
isHA = input.bool(false, "Use HA Candles")
src = isHA ? sources : sources

// Sampling Period
per = input.int(defval=50, minval=1, title="Sampling Period")

// Range Multiplier
mult = input.float(defval=3.0, minval=0.1, title="Range Multiplier")

// Smooth Average Range
smoothrng(x, t, m)=>
    wper = (t * 2) - 1
    avrng = ta.ema(math.abs(x - x[1]), t)
    smoothrng = ta.ema(avrng, wper) * m
    smoothrng
smrng = smoothrng(src, per, mult)

// Range Filter
rngfilt(x, r)=>
    rngfilt = x
    rngfilt := x > nz(rngfilt[1]) ? ((x - r) < nz(rngfilt[1]) ? nz(rngfilt[1]) : (x - r)) : ((x + r) > nz(rngfilt[1]) ? nz(rngfilt[1]) : (x + r))
    rngfilt
filt = rngfilt(src, smrng)

// Filter Direction
var float upward = 0.0
upward := filt > filt[1] ? nz(upward[1]) + 1 : filt < filt[1] ? 0 : nz(upward[1])
var float downward = 0.0
downward := filt < filt[1] ? nz(downward[1]) + 1 : filt > filt[1] ? 0 : nz(downward[1])

// Target Bands
hband = filt + smrng
lband = filt - smrng

// Plot target bands
//plot(hband, color=color.aqua, title="High Target")
//plot(lband, color=color.fuchsia, title="Low Target")

// Breakout conditions
bool longCond = na
bool shortCond = na
longCond := ((src > filt) and (src > src[1]) and (upward > 0)) or ((src > filt) and (src < src[1]) and (upward > 0))
shortCond := ((src < filt) and (src < src[1]) and (downward > 0)) or ((src < filt) and (src > src[1]) and (downward > 0))

var int CondIni = 0
CondIni := longCond ? 1 : shortCond ? -1 : CondIni[1]
longCondition = longCond and CondIni[1] == -1
shortCondition = shortCond and CondIni[1] == 1

// Plot Buy and Sell signals on chart
plotshape(series=longCondition, title="Buy Signal", text="BUY", textcolor=color.white, style=shape.triangleup, size=size.small, location=location.belowbar, color=color.green)
plotshape(series=shortCondition, title="Sell Signal", text="SELL", textcolor=color.white, style=shape.triangledown, size=size.small, location=location.abovebar, color=color.red)

// Create alert conditions for Buy and Sell signals
alertcondition(longCondition, title="Buy Alert", message="Buy Signal Triggered!")
alertcondition(shortCondition, title="Sell Alert", message="Sell Signal Triggered!")
